name: Android CI

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'zulu'
        cache: gradle
        
    - name: Setup Firebase CLI
      uses: pocket-apps/action-setup-firebase@v2
      with:
        # Firebase token you can get by running `firebase login:ci`
        firebase-token: ${{secrets.FIREBASE_TOKEN}}
        
    - name: Create google-services.json
      run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > ./app/google-services.json

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: build debug 
      run: ./gradlew bundleDebug
      
    - name: Run unit tests
      run: ./gradlew testDebugUnitTest
      
    - name: upload debug artifact to Firebase App Distribution
      run: firebase appdistribution:distribute app/build/outputs/bundle/debug/app-debug.aab --token ${{secrets.FIREBASE_TOKEN}} --app ${{secrets.FIREBASE_APP_ID}} --testers "kbg0412@gmail.com" --release-notes "Test Distribution"
    
    - name: action-slack
      uses: 8398a7/action-slack@v3.14.0
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      env:
         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()
